name: Check zendo metadata

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install zenodraft
      - name: Check .zenodo.json file
        run: |
          npx zenodraft metadata validate .zenodo.json 
